
const { expect, browser } = require('@wdio/globals');
const { goToPage, goToSubmenu } = require('./sidebar');
const isVortex = require('../test-data/testdata').isVortex

const delay = (ms) => {
    return new Promise(res => {
       setTimeout(() => {
        res()
       }, ms) 
    })
}

const mainLink = require('../test-data/testLink').Link.BULK_EMAIL_LINK;

describe('Test Data Setup', () => {
    describe('Preparation', () => {
        it('Delete Tester Contact', async () => {
            await goToPage('contacts')
            let testingContactElement = await $('span=' + 'Tester Joe')
            const testingElementExist = await testingContactElement.isDisplayed()
            if(testingElementExist) {
                await delay(3000)
                const testingContactTr = await browser.custom$('closest', testingContactElement)
                const selectEl = await testingContactTr.$('td.mat-column-select')
                await selectEl.scrollIntoView()
                await browser.execute(ele => {
                    ele.querySelector("input[type='checkbox']").click()
                }, selectEl)
                await $('div[data-name="material-action-item-More"]').waitForClickable({ timeout: 2000 })
                await $('div[data-name="material-action-item-More"]').click()
                await $('div[data-name="material-action-item-More-Delete"]').click()
                await $('button[data-action="confirm-downgrade"]').click()
                await delay(5000)
            }
        })
    })
})
describe('New Bulk Email', () => {
    it('New Email Template', async () => {
        await goToPage('bulkEmail')
        await $('a[data-action="add-new-bulk-email"]').click()
        await delay(3000)
        await $('input[name="campaign_name"]').setValue('bulk email test')
        await delay(3000)
        await $('div[data-name="bulk-email-new-template"]').waitForClickable({ timeout: 3000 })
        await $('div[data-name="bulk-email-new-template"]').click()
        await $('div[data-name="bulk-email-new-email-template"]').click()
        await $('app-campaign-create app-template input').setValue('test')
        await browser.execute((text) => {
            document.querySelector('app-html-editor quill-editor[data-name="deal-action-description"] .ql-editor').innerHTML = text;
        }, '<div>test bulk mail content</div>');
        await $('button[data-action="bulk-email-save-btn"]').click()
        await $('button[data-action="bulk-email-next1"]').waitForClickable({ timeout: 5000 })
        await $('button[data-action="bulk-email-next1"]').click()
        await $('button[data-action="bulk-email-select-contact"]').click()
        await $('app-campaign-add-contact').waitForDisplayed({ timeout: 5000 })
        await delay(2000)
        const selectEl = await $('app-campaign-add-contact table tbody tr:first-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector('input[type="checkbox"]').click();
        }, selectEl)
        await $('button[data-action="bulk-email-contact-add"]').click()
        await $('app-campaign-add-contact').waitForDisplayed({ reverse: true })
        await delay(2000)
        await $('button[data-action="bulk-email-next-btn3"]').click()
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').waitForClickable({ timeout: 3000 })
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').click()
        await $('app-business-date-time-picker div.cal-days > div:nth-of-type(3) mwl-calendar-month-cell:nth-of-type(3) div.cal-cell-top span.cal-day-number').click()
        await $('button[data-action="bulk-email-next-btn4"]').click()
        await $('button[data-action="bulk-email-submit-btn"]').waitForClickable({ timeout: 3000 })
        await $('button[data-action="bulk-email-submit-btn"]').click()
        await delay(5000)
        await expect($('table tbody tr:last-of-type td.mat-column-title a')).toHaveText('bulk email test')
        await expect($('table tbody tr:last-of-type td.mat-column-status')).toHaveText('Awaiting')
        await delay(3000)
        // Delete
        const selectEl1 = await $('app-campaign-bulk-mailing table tbody tr:last-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector("input[type='checkbox']").click();
        }, selectEl1)
        await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
        await $('div[data-name="material-action-item-Delete"]').click()
        await $('app-confirm button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 2000 })
        await $('app-confirm button[data-action="confirm-downgrade"]').click()
        await delay(5000)
    })
    it('Existing Newsletter Template', async () => {
        await goToPage('bulkEmail')
        await $('a[data-action="add-new-bulk-email"]').click()
        await delay(3000)
        await $('input[name="campaign_name"]').setValue('existing newsletter test')
        await delay(3000)
        await $('button[data-action="bulk-email-select-template"]').click()
        await $('app-templates-browser').waitForDisplayed({ timeout: 2000 })
        await $('app-templates-browser table tbody tr:first-of-type td.mat-column-title span').click()
        await $('app-templates-browser button[type="submit"]').click()
        await $('app-templates-browser').waitForDisplayed({ reverse: true })
        await $('button[data-action="bulk-email-next1"]').click()
        await $('button[data-action="bulk-email-select-contact"]').click()
        await $('app-campaign-add-contact').waitForDisplayed({ timeout: 5000 })
        await delay(2000)
        const selectEl = await $('app-campaign-add-contact table tbody tr:first-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector('input[type="checkbox"]').click();
        }, selectEl)
        await $('button[data-action="bulk-email-contact-add"]').click()
        await $('app-campaign-add-contact').waitForDisplayed({ reverse: true })
        await delay(2000)
        await $('button[data-action="bulk-email-next-btn3"]').click()
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').waitForClickable({ timeout: 3000 })
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').click()
        await $('app-business-date-time-picker div.cal-days > div:nth-of-type(3) mwl-calendar-month-cell:nth-of-type(3) div.cal-cell-top span.cal-day-number').click()
        await $('button[data-action="bulk-email-next-btn4"]').click()
        await $('button[data-action="bulk-email-submit-btn"]').click()
        await delay(5000)
        await expect($('table tbody tr:last-of-type td.mat-column-title a')).toHaveText('existing newsletter test')
        await expect($('table tbody tr:last-of-type td.mat-column-status')).toHaveText('Awaiting')
        await delay(3000)
        // Delete
        const selectEl1 = await $('app-campaign-bulk-mailing table tbody tr:last-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector('input[type="checkbox"]').click();
        }, selectEl1)
        await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
        await $('div[data-name="material-action-item-Delete"]').click()
        await $('app-confirm button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 2000 })
        await $('app-confirm button[data-action="confirm-downgrade"]').click()
        await delay(5000)
    })
    it('New Email Add Contact', async () => {
        await goToPage('bulkEmail')
        await $('a[data-action="add-new-bulk-email"]').click()
        await delay(3000)
        await $('input[name="campaign_name"]').setValue('bulk email test 2')
        await delay(3000)
        await $('div[data-name="bulk-email-new-template"]').click()
        await $('div[data-name="bulk-email-new-email-template"]').click()
        await $('app-campaign-create app-template input').setValue('test')
        await browser.execute((text) => {
            document.querySelector('quill-editor[data-name="deal-action-description"] .ql-editor').innerHTML = text;
        }, '<div>test bulk mail content</div>');
        await $('app-campaign-create app-template i.i-insert-material').click()
        await delay(3000)
        const selectEl = await $('app-material-browser-v2 div.material-list > div:last-of-type div[data-action="toggle-selected-material"]')
        await browser.execute(ele => {
            ele.querySelector('input[type="checkbox"]').click();
        }, selectEl)
        await $('app-material-browser-v2').$('button=Insert').click()
        await delay(2000)
        await $('button[data-action="bulk-email-save-btn"]').click()
        await $('button[data-action="bulk-email-next1"]').waitForClickable({ timeout: 5000 })
        await $('button[data-action="bulk-email-next1"]').click()
        await $('button[data-action="bulk-email-new-contact"]').click()
        await $('app-contact-create-edit').waitForDisplayed({ timeout: 2000 })
        await delay(3000)
        await $('input[data-name="contact-create-firstname"]').setValue('Tester')
        await delay(3000)
        await $('input[data-name="contact-create-lastname"]').setValue('Joe')
        await delay(3000)
        await $('input[data-name="contact-create-email"]').setValue('tester.joe1@crmgrow.com')
        await delay(3000)
        await $('app-phone-input input[data-name="add-user-phone"]').setValue('9192839374')
        await delay(3000)
        await $('button[data-action="create-contact-add-btn"]').click()
        await $('app-contact-create-edit').waitForDisplayed({ reverse: true })
        await $('button[data-action="bulk-email-next-btn3"]').click()
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').waitForClickable({ timeout: 3000 })
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').click()
        await $('app-business-date-time-picker div.cal-days > div:nth-of-type(3) mwl-calendar-month-cell:nth-of-type(3) div.cal-cell-top span.cal-day-number').click()
        await $('button[data-action="bulk-email-next-btn4"]').click()
        await $('button[data-action="bulk-email-submit-btn"]').click()
        await delay(5000)
        await expect($('table tbody tr:last-of-type td.mat-column-title a')).toHaveText('bulk email test 2')
        await expect($('table tbody tr:last-of-type td.mat-column-status')).toHaveText('Awaiting')
        await delay(3000)
        // Delete
        const selectEl1 = await $('app-campaign-bulk-mailing table tbody tr:last-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector("input[type='checkbox']").click()
        }, selectEl1)
        await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
        await $('div[data-name="material-action-item-Delete"]').click()
        await $('app-confirm button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 2000 })
        await $('app-confirm button[data-action="confirm-downgrade"]').click()
        await delay(3000)
        // Remove test contact
        await goToPage('contacts')
        await delay(7000)
        const testContactExist = await $('span=Tester Joe').isDisplayed()
        if(testContactExist) {
            await $('span=Tester Joe').click()
            await delay(5000)
            await $('div[data-name="contact-dropdown-toggle"]').waitForClickable({ timeout: 5000 })
            await $('div[data-name="contact-dropdown-toggle"]').click()
            await $('button[data-action="contact-action-delete"]').waitForClickable({ timeout: 2000 })
            await $('button[data-action="contact-action-delete"]').click()
            await $('button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 3000 })
            await $('button[data-action="confirm-downgrade"]').click()
            await delay(5000)
            await expect($('span=Tester Joe')).not.toExist()
            await delay(3000)
        }
    })
    it('New Newsletter Add Contact', async () => {
        await goToPage('bulkEmail')
        await $('a[data-action="add-new-bulk-email"]').click()
        await delay(3000)
        await $('input[name="campaign_name"]').setValue('newsletter test 2')
        await delay(3000)
        await $('div[data-name="bulk-email-new-template"]').click()
        await $('div[data-name="bulk-email-new-template-newsletter"]').click()
        await delay(10000)
        await $('input[name="title"]').setValue('newsletter test 2')
        await delay(3000)
        await $('input[name="subject"]').setValue('BBC news')
        await delay(3000)
        await $('button[data-action="create-newsletter-start-from-template"]').click()
        await $('app-import-templates').waitForDisplayed({ timeout: 2000 })
        await delay(10000)
        await $('div.templates div.template:first-of-type div.thumbnail').moveTo()
        await $('div.templates div.template:first-of-type div.overlay div.action button.btn-primary').waitForClickable({ timeout: 10000 })
        await $('div.templates div.template:first-of-type div.overlay div.action button.btn-primary').click()
        await $('app-import-templates').waitForDisplayed({ reverse: true })
        await delay(20000)
        await $('button[data-action="create-newsletter-save"]').click()
        await delay(20000)
        await $('button[data-action="bulk-email-next1"]').waitForClickable({ timeout: 20000 })
        await $('button[data-action="bulk-email-next1"]').click()
        await $('button[data-action="bulk-email-new-contact"]').click()
        await $('app-contact-create-edit').waitForDisplayed({ timeout: 2000 })
        await delay(3000)
        await $('input[data-name="contact-create-firstname"]').setValue('Tester')
        await delay(3000)
        await $('input[data-name="contact-create-lastname"]').setValue('Joe')
        await delay(3000)
        await $('input[data-name="contact-create-email"]').setValue('tester.joe1@crmgrow.com')
        await delay(3000)
        await $('app-phone-input input[data-name="add-user-phone"]').setValue('9192839374')
        await delay(3000)
        await $('button[data-action="create-contact-add-btn"]').click()
        await $('app-contact-create-edit').waitForDisplayed({ reverse: true })
        await $('button[data-action="bulk-email-next-btn3"]').click()
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').waitForClickable({ timeout: 3000 })
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').click()
        await $('app-business-date-time-picker div.cal-days > div:nth-of-type(3) mwl-calendar-month-cell:nth-of-type(3) div.cal-cell-top span.cal-day-number').click()
        await $('button[data-action="bulk-email-next-btn4"]').click()
        await $('button[data-action="bulk-email-submit-btn"]').click()
        await delay(5000)
        await expect($('table tbody tr:last-of-type td.mat-column-title a')).toHaveText('newsletter test 2')
        await expect($('table tbody tr:last-of-type td.mat-column-status')).toHaveText('Awaiting')
        await delay(3000)
        // Delete
        const selectEl = await $('app-campaign-bulk-mailing table tbody tr:last-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector("input[type='checkbox']").click()
        }, selectEl)
        await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
        await $('div[data-name="material-action-item-Delete"]').click()
        await $('app-confirm button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 2000 })
        await $('app-confirm button[data-action="confirm-downgrade"]').click()
        await delay(3000)
        // Remove test contact
        await goToPage('contacts')
        const testContactExist = await $('span=Tester Joe').isExisting()
        if(testContactExist) {
            await $('span=Tester Joe').click()
            await delay(5000)
            await $('div[data-name="contact-dropdown-toggle"]').waitForClickable({ timeout: 5000 })
            await $('div[data-name="contact-dropdown-toggle"]').click()
            await $('button[data-action="contact-action-delete"]').waitForClickable({ timeout: 2000 })
            await $('button[data-action="contact-action-delete"]').click()
            await $('button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 3000 })
            await $('button[data-action="confirm-downgrade"]').click()
            await delay(5000)
            await expect($('span=Tester Joe')).not.toExist()
            await delay(3000)
        }
        // Newletter Clear
        await $('div[data-name="sidebar-item-bulk_email"] > a').click()
        await delay(3000)
        await $('span[data-name="profile-tab-item-Newsletters"]').waitForClickable({ timeout: 5000 })
        await $('span[data-name="profile-tab-item-Newsletters"]').click()
        const testNewsletterExist = await $('a=newsletter test 2').isDisplayed()
        if(testNewsletterExist) {
            const testNewsletter = await $('a=newsletter test 2')
            const testNewsletterTr = await browser.custom$('closest', testNewsletter)
            const selectEl1 = await testNewsletterTr.$('td.mat-column-select')
            await browser.execute(ele => {
                ele.querySelector("input[type='checkbox']").click()
            }, selectEl1)
            await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
            await $('div[data-name="material-action-item-Delete"]').click()
            await $('app-confirm').waitForDisplayed({ timeout: 3000 })
            await $('app-confirm button[data-action="confirm-downgrade"]').click()
            await $('app-confirm').waitForDisplayed({ reverse: true })
            await delay(3000)
        }
    })
    it('Existing Newsletter Add Contact', async () => {
        await goToPage('bulkEmail')
        await $('a[data-action="add-new-bulk-email"]').click()
        await delay(3000)
        await $('input[name="campaign_name"]').setValue('existing newsletter test 2')
        await delay(3000)
        await $('button[data-action="bulk-email-select-template"]').click()
        await $('app-templates-browser').waitForDisplayed({ timeout: 2000 })
        await $('app-templates-browser table tbody tr:first-of-type td.mat-column-title span').click()
        await $('app-templates-browser button[type="submit"]').click()
        await $('app-templates-browser').waitForDisplayed({ reverse: true })
        await $('button[data-action="bulk-email-next1"]').click()
        await $('button[data-action="bulk-email-new-contact"]').click()
        await $('app-contact-create-edit').waitForDisplayed({ timeout: 2000 })
        await delay(3000)
        await $('input[data-name="contact-create-firstname"]').setValue('Tester')
        await delay(3000)
        await $('input[data-name="contact-create-lastname"]').setValue('Joe')
        await delay(3000)
        await $('input[data-name="contact-create-email"]').setValue('tester.joe1@crmgrow.com')
        await delay(3000)
        await $('app-phone-input input[data-name="add-user-phone"]').setValue('9192839374')
        await delay(3000)
        await $('button[data-action="create-contact-add-btn"]').click()
        await $('app-contact-create-edit').waitForDisplayed({ reverse: true })
        await $('button[data-action="bulk-email-next-btn3"]').click()
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').waitForClickable({ timeout: 3000 })
        await $('app-business-date-time-picker div.calendar-wrapper i.i-chev-right').click()
        await $('app-business-date-time-picker div.cal-days > div:nth-of-type(3) mwl-calendar-month-cell:nth-of-type(3) div.cal-cell-top span.cal-day-number').click()
        await $('button[data-action="bulk-email-next-btn4"]').click()
        await $('button[data-action="bulk-email-submit-btn"]').click()
        await $('table').waitForDisplayed({ timeout: 6000 })
        await expect($('table tbody tr:last-of-type td.mat-column-title a')).toHaveText('existing newsletter test 2')
        await expect($('table tbody tr:last-of-type td.mat-column-status')).toHaveText('Awaiting')
        await delay(3000)
        // Delete
        const selectEl = await $('app-campaign-bulk-mailing table tbody tr:last-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector("input[type='checkbox']").click()
        }, selectEl)
        await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
        await $('div[data-name="material-action-item-Delete"]').click()
        await $('app-confirm button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 2000 })
        await $('app-confirm button[data-action="confirm-downgrade"]').click()
        await delay(3000)
        // Remove test contact
        await goToPage('contacts')
        await delay(7000)
        const testContactExist = await $('span=Tester Joe').isExisting()
        if(testContactExist) {
            await $('span=Tester Joe').click()
            await delay(5000)
            await $('div[data-name="contact-dropdown-toggle"]').waitForClickable({ timeout: 5000 })
            await $('div[data-name="contact-dropdown-toggle"]').click()
            await $('button[data-action="contact-action-delete"]').waitForClickable({ timeout: 2000 })
            await $('button[data-action="contact-action-delete"]').click()
            await $('button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 3000 })
            await $('button[data-action="confirm-downgrade"]').click()
            await delay(5000)
            await expect($('span=Tester Joe')).not.toExist()
            await delay(3000)
        }
    })
    it('New Newsletter', async () => {
        await goToPage('bulkEmail')
        await $('span[data-name="profile-tab-item-Newsletters"]').click()
        await $('a[data-action="bulk-email-create-new-newsletter"]').click()
        await delay(10000)
        await $('input[name="title"]').setValue('Topping')
        await $('input[name="subject"]').setValue('BBC news')
        await delay(3000)
        await $('div.insert-token div.no-carot').click()
        await $('div.insert-token div.light > div:first-of-type').click()
        await $('button[data-action="create-newsletter-start-from-template"]').click()
        await $('app-import-templates').waitForDisplayed({ timeout: 2000 })
        await delay(10000)
        await $('div.templates div.template:first-of-type div.thumbnail').moveTo()
        await $('div.templates div.template:first-of-type div.overlay div.action button.btn-primary').waitForClickable({ timeout: 3000 })
        await $('div.templates div.template:first-of-type div.overlay div.action button.btn-primary').click()
        await $('app-import-templates').waitForDisplayed({ reverse: true })
        await delay(12000)
        await $('button[data-action="create-newsletter-save"]').click()
        await delay(20000)
        await $('div[data-name="sidebar-item-bulk_email"] > a').click()
        await $('span[data-name="profile-tab-item-Newsletters"]').waitForClickable({ timeout: 5000 })
        await $('span[data-name="profile-tab-item-Newsletters"]').click()
        await delay(3000)
        await expect($('app-campaign-templates table tbody tr:last-of-type td.mat-column-title a')).toHaveText('Topping')
        await delay(3000)
        // Delete
        const selectEl = await $('app-campaign-templates table tbody tr:last-of-type td.mat-column-select')
        await browser.execute(ele => {
            ele.querySelector("input[type='checkbox']").click();
        }, selectEl)
        await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
        await $('div[data-name="material-action-item-Delete"]').click()
        await $('app-confirm button[data-action="confirm-downgrade"]').waitForClickable({ timeout: 2000 })
        await $('app-confirm button[data-action="confirm-downgrade"]').click()
        await delay(5000)
        // Newletter Clear
        await $('div[data-name="sidebar-item-bulk_email"] > a').click()
        await delay(3000)
        await $('span[data-name="profile-tab-item-Newsletters"]').waitForClickable({ timeout: 5000 })
        await $('span[data-name="profile-tab-item-Newsletters"]').click()
        const testNewsletterExist = await $('a=Topping').isDisplayed()
        if(testNewsletterExist) {
            const testNewsletter = await $('a=Topping')
            const testNewsletterTr = await browser.custom$('closest', testNewsletter)
            const selectEl1 = await testNewsletterTr.$('td.mat-column-select')
            await browser.execute(ele => {
                ele.querySelector("input[type='checkbox']").click();
            }, selectEl1)
            await $('div[data-name="material-action-item-Delete"]').waitForClickable({ timeout: 3000 })
            await $('div[data-name="material-action-item-Delete"]').click()
            await $('app-confirm').waitForDisplayed({ timeout: 3000 })
            await $('app-confirm button[data-action="confirm-downgrade"]').click()
            await $('app-confirm').waitForDisplayed({ reverse: true })
            await delay(3000)
        }
    })
})
